---
- name: Install gdal system package
  apt:
    name:
      - gdal-bin
      - libgdal-dev
      - libmapnik-dev
  become: true
  become_user: root

- name: Set gdal version as a fact for xenial
  set_fact:
    gdal_version: "1.11.2"
  when: ansible_distribution_version == "16.04"

- name: Set gdal version as a fact for bionic
  set_fact:
    gdal_version: "2.2.3"
  when: ansible_distribution_version == "18.04"

- name: Install gdal python bindings
  environment:
    CPLUS_INCLUDE_PATH: /usr/include/gdal
    C_INCLUDE_PATH: /usr/include/gdal
  pip:
    name: gdal
    virtualenv: "{{ large_image_virtualenv }}"
    version: "{{ gdal_version }}"

- name: Install python dependencies for mapnik tile source
  pip:
    name:
      - mapnik
      - palettable
      - pyproj
    virtualenv: "{{ large_image_virtualenv }}"
